### ISSUE TITLE
GIFs do not send correctly

### ISSUE THREAD

**Issue by edintomato** [wireapp/wire-ios#1630] opened 2018-01-22 12:59 UTC
* [x] I checked the existing issues, and the issue was not reported before.

## The problem

When someone using an iOS device sends a GIF through Wire, the GIF plays once or does not play at all. The iOS user can see and play GIFs just fine from other, non iOS devices.

## Environment

* Wire version that exhibits the issue: 3.5
* Last Wire version that did not exhibit the issue (if applicable): 1.0
* iOS version used to run Wire: 11.2
* iOS device type: iPad
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi
* Exact date, time and timezone (only for the crash issues): 

## Details

Send a GIF through Wire from an iOS device. The GIF sends, but does not repeat.

## Screenshots

You can't take a screenshot of a moving image.

**Comment by emuNAND** [comment] 2018-01-22 13:04
![wire_ios](https://user-images.githubusercontent.com/22921456/35222059-94824cfa-ff4a-11e7-9ebd-24910cb01f52.gif)
![wire_android](https://user-images.githubusercontent.com/22921456/35222080-a1f6b9d4-ff4a-11e7-9ea8-8b6ca168c4ac.gif)

The top GIF is the GIF iOS sends. The bottom one is the GIF Android sends.

**Comment by mikeger** [comment] 2018-01-22 13:19
Hey @emuNAND ! Thanks for reporting an issue! I can see how this client behavior is annoying to the user. However it is currently as designed, and let me explain why.

The conversation messages can be of several types: images, text, files. 
- Images are downloaded automatically as they have to be displayed. 
- Text is fetched and decrypted from backend when client sees that there is a new message.
- Files are the only type of content that is downloaded on user's demand.

We are explicitly limiting the size of the image that can be uploaded, since the images are downloaded automatically, and this can be an issue for the people who are using the mobile data, since the images are downloaded automatically.

For example, the GIF in this post is 4.5 MB big, depending on the country it can be pretty painful for the data plan to fetch it, even if we are caching the data on the device.

The current behavior that the client is not warning the sender that it's going to send the still image is not acceptable, and we should fix it, however for the data plan issue the fix should not be that we would just allow sending the bigger image, but some way of downloading the image on demand.

**Comment by kyle-fox** [comment] 2018-01-22 20:42
@mikeger Ohhhh! Since that's not indicated anywhere in the UI, this is also most likely the cause of the other open gif issue in https://github.com/wireapp/wire-ios/issues/836. Would love to see UI for this and options for on demand download or download on wifi options 👍

**Comment by 0ki** [comment] 2018-01-23 23:29
Two things are annoying about this.
1) it happens randomly.
2) it was working perfectly "before", e.g. the "fix" @mikeger is describing has caused regression.

**Comment by cardassian-tailor** [comment] 2018-01-31 16:53
Is the default behavior to automatically download and load the full GIF if the receiving end is on wifi? That would make sense.

**Comment by billypchan** [comment] 2019-06-07 09:22
This issue is fixed in https://github.com/wireapp/wire-ios-images/pull/30.

**Comment by billypchan** [comment] 2019-07-31 11:47
fix included in v3.40

**Closed by billypchan** 2019-07-31 11:47 UTC
Labels: Bug, Easy contribution
