### ISSUE TITLE
Notification for new messages often just shows "New message" / "Neue Nachricht"

### ISSUE THREAD

**Issue by rbieb** [wireapp/wire-ios#662] opened 2017-02-04 15:29 UTC
![fullsizeoutput_7e8](https://cloud.githubusercontent.com/assets/6862450/22619558/0cde2958-eaf7-11e6-9fd1-25267cb259c3.jpeg)

Only happens once every while, but it's still frustrating.

**Comment by jenskasemets** [comment] 2017-02-20 14:25
Hi @rbieb,

Here's small explanation why you see such notifications.
This is so-called fallback notification. In normal conditions your device receives push notification for each message with actual encrypted content, then your application decrypts the message and decides what to do with it: for text messages, images etc a notification is shown for the user. For system messages (delivery receipts etc) it just updates local content status.
After that app informs our backend that it was successfully decrypted. In the case our backend is not informed about it in 30 seconds, then another push notification is sent, without actual content (because we don't know the content of that push notification), saying just "New message". 
If you are online and there are no long delay with push notification sending, this should happen really rarely.
Limitation is that we will send fallback notification for all types of messages, not just text, image, call etc, but also for likes and delivery receipts — because we don't have a way to see inside the message to detect what it includes. That's why sometimes you open app and don't see new content, despite maybe someone liked your older message (this issue will be addressed in near future separately).

This is designed behaviour and currently there's no plan to change it, otherwise it will influence users privacy.

**Closed by jenskasemets** 2017-02-20 14:25 UTC

**Comment by MadEgg** [comment] 2017-02-23 12:34
As mentioned in #685 - this happens to me on a regular basis, especially when I turn on my phone in the morning and I received messages while my phone was turned off. Is this also still by design?

No clue about the implementation, but wouldn't it be possible to refer to the message by some kind of hash / sequence / ID-code so that you don't transmit the contents more than once, but the app just gets a poke 'Hey, there is this message you should inform the user about'. The Wire app should know the contents of the message so it can generate a more informative notification for the user.

**Comment by anatoli26** [comment] 2017-02-27 13:33
I agree with MadEgg, there are possibilities to indicate to the app about the type of notification without exposing anything sensible.

Also, as Wire is a VoIP app, you can use PushKit notifications that are almost real-time and they may wake the app up without notifying the user in any way. So you could send these "invisible" notifications for alerts that don't produce any new content (so the app wakes up and receives the updates) and send common notifications setting the badge counter for new messages.

**Comment by dbquarrel** [comment] 2017-07-16 02:00
I think this can be triggered by the other party in a conversation doing a "delete for everyone" as well. 

Something has to be thought about this because myself, and my contacts, we are constantly saying "Wire gave me an update that a message came in but I didn't see any message. Did you send me something?" 

I get that message once per day from different people.

So, please think about this behavior as it is definitely non-ideal and confusing. People are under the impression that they are losing messages and that causes a deterioration in faith in the product and will make the adopt something else.
