### ISSUE TITLE
iOS 11 Cannot record voice memos

### ISSUE THREAD

**Issue by wangkesen** [wireapp/wire-ios#1084] opened 2017-06-12 18:55 UTC
This is a bug with iOS 11, which is still on the developers build so it may be a problem with the iOS and not with Wire itself but just wanted to flag the bug unless their is an issue with how Wire runs on iOS 11 and not just with iOS.

Description: Voice memo records as usual but upon completion and stopping the recording, voice memo shows as blank, pressing send is unresponsive.
![](http://i.imgur.com/fii7li9.jpg)
![](http://i.imgur.com/8pWb0uH.jpg)

**Comment by mikeger** [comment] 2017-06-16 12:12
Hey @wangkesen , thanks for reporting the issue. We'll acknowledge this one, but it's also frequently happening that Apple's beta versions are having the issues that are going to be fixed from Apple's side. In this case the work we could potentially spend now debugging it would be lost. We'll wait for beta 3 release to tackle this one.

**Comment by wangkesen** [comment] 2017-06-25 06:18
Sure! Thanks for replying. For future reference is it okay to use Github as a platform for opening issues or does Wire prefer just messaging then or contacting via Twitter, etc?

**Comment by mikeger** [comment] 2017-06-26 07:46
Hey, the preferred way currently is to reach out via support channels, like https://support.wire.com/hc/en-us

**Comment by mikeger** [comment] 2017-11-15 16:13
Hey @wangkesen , I think the issue is fixed now, can you confirm?

**Comment by mikeger** [comment] 2017-11-27 10:02
Fixed in the current version.

**Closed by mikeger** 2017-11-27 10:02 UTC
Labels: Bug
