### ISSUE TITLE
Missing notification badge

### ISSUE THREAD

**Issue by gapop** [wireapp/wire-ios#2008] opened 2018-04-13 15:50 UTC
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

The problem was reported before, but in very different usage scenario. See #685 and #761.

## The problem

Since the latest update, the red notification badge that shows the number of messages no longer appears when receiving new messages. The banner notification does appear, but no badge. Very rarely, the badge will appear _after_ opening the app to read the message, so I have to open the app a second time to make the badge disappear.

Badge notifications are activated for the app in iOS notification preferences. All options are enabled, "When Unlocked" option is selected for message previews.

## Environment

* Wire version that exhibits the issue: 3.10 (3000)
* Last Wire version that did not exhibit the issue (if applicable): previous version
* iOS version used to run Wire: 11.3 (15E216)
* iOS device type: iPhone 8
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi, 3G and 4G (same behaviour regardless)

**Comment by mikeger** [comment] 2018-04-20 09:46
Hey, this would be fixed in Wire 3.11, here was the fix: https://github.com/wireapp/wire-ios-sync-engine/pull/744

**Comment by mikeger** [comment] 2018-05-02 16:13
Hey, can you confirm that the issue is fixed now? Thanks!

**Comment by gapop** [comment] 2018-05-02 16:15
Yes, it was fixed for me after upgrade to the latest version. Thank you.

**Closed** 2018-05-03 08:37 UTC
