### ISSUE TITLE
Cannot edit message in sending or send failed state

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#413] opened 2016-11-20 14:02 UTC
On iOS, we cannot edit message in sending or send failed state.

Scenario: 
* sending a message with mistake
* see it in sending or failed state and wanting to catch the chance to correct it before the effective sending

**Comment by jenskasemets** [comment] 2016-11-21 09:53
Thank you for the feedback. This behaviour is currently like that by design, because it means client might wait for the answer from the backend, editing content of the message would mean it needs to be resend again after answer from backend is received.
We have actually alternative solution for that coming in next release: you can delete messages in these states, this solves your problem (which should not happen too often anyway) and also avoids inconsistent between sender and receiver. 

If you agree, I would like to close this issue as we are not planning to implement such complex behaviour and think deleting message is nicer and cleaner solution.

**Comment by IpsmLorem** [comment] 2016-11-21 20:25
Thank you for your reply, your future feature is a valid work around.

**Comment by jenskasemets** [comment] 2016-11-30 13:18
Option to delete messages in "sending" or "failed" states is now available in release 2.23

**Closed by jenskasemets** 2016-11-30 13:18 UTC
Labels: Feature request
