### ISSUE TITLE
Wire audio and video calls do not work when connected to cellular network (LTE)

### ISSUE THREAD

**Issue by dfarr24** [wireapp/wire-ios#2375] opened 2018-07-05 14:27 UTC
## Checklist (please check before submitting)

* [X ] I checked the existing issues, and the issue was not reported before.

## The problem

When attempting to call another user on Wire via audio or video and connected to the cellular network, the other user does not get notified that the call is coming through. It works perfectly when connected to WiFi.

## Environment

* Wire version that exhibits the issue: 3.16 (3052)
* Last Wire version that did not exhibit the issue (if applicable):
* iOS version used to run Wire: 11.4
* iOS device type: iPhone 7/ X
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE
* Exact date, time and timezone (only for the crash issues): 

## Details

1. Initiate call from mobile device connected to LTE network, wire says it's ringing the other user.
2. Other user never gets notified on their device that a call is coming through at all.

If the user being called is on Wi-Fi and the calling user is on LTE, the called user does get a notification but when they try to accept the call it does not go through.

Calling via audio and video works great when both parties are connected via Wi-Fi.

## Calling Debug logs (only for calling issues)

0. You have to have the iOS email client set up.
1. Reproduce the issue.
2. Go to Settings -> Advanced -> Calling Debug Report.
3. Send the report.

## Screenshots

Please attach screenshots if you consider them as helpful to understand/reproduce the issue.

**Comment by vytis** [comment] 2018-07-05 14:34
@dfarr24 thanks for opening the issue. This sounds like a very common scenario and probably the root cause is something else. To be able to see what is going on we need calling debug logs which you can send from app Settings (Settings -> Advanced -> Calling Debug Report -> Send). Make sure to send the logs after experiencing the issue with a call. We don't save the information to disk and it disappears after using the app for some time.

**Comment by dfarr24** [comment] 2018-07-05 14:36
Thanks for getting back to me so soon. I already sent my debug logs via the app. I was testing it yesterday with various use cases so there will be at least one successful call complete in there when myself and the other user were on WiFi.

**Comment by vytis** [comment] 2018-07-05 14:44
Great, if you sent the logs already our customer support should contact you soon asking about more information. Useful things to say there - how many calls you had, which ones were fine and which ones failed. Network conditions and any other details could also make it easier for us to debug it.

**Comment by vytis** [comment] 2018-07-06 15:24
I will close the issue then, it will be tracked through customer support.

**Closed by vytis** 2018-07-06 15:24 UTC

**Comment by dfarr24** [comment] 2018-07-10 14:21
To close the loop on this, I was told that since my cellular provider uses IPv6, calls will not work because wire does not yet support IPv6. They are working on it now.
