### ISSUE TITLE
Message timestamps missing since 2.15

### ISSUE THREAD

**Issue by 0ki** [wireapp/wire-ios#249] opened 2016-09-26 17:01 UTC
I was able to view exact time of any received or sent message by tapping on it.
Since the introduction on the "like" feature, I am not able to do that for most messages on an iPhone.
I'd like that back.

(Or has the feature moved somewhere else and I just don't know how to access it anymore?)

**Comment by typfel** [comment] 2016-09-26 20:26
Hi, thanks for the feedback. What do you see when you that on a message? You should still be able to see the timestamp by tapping on a message, however we do show a tutorial message until you've liked your first message.

**Comment by 0ki** [comment] 2016-09-26 23:45
I think I see the tutorial message and that prevents me from seeing the timestamp.

**Comment by KoalaBoomka** [comment] 2016-09-27 08:31
Hi, @0ki! 
If the issue is solved, it would be really nice to close it.

**Comment by 0ki** [comment] 2016-09-27 09:31
I do not believe it's truly solved. Sure it's just a usability bug now that you've explained it, but I believe tutorial should not replace old behaviour that users are accustomed to.

**Comment by KoalaBoomka** [comment] 2016-09-27 09:35
@0ki, this is an improvement for the like feature for helping users to discover it. After the first like, tutorial will disappear and wouldn't bother you ever again.

**Comment by 0ki** [comment] 2016-09-27 09:40
I understand that, but only by the virtue of being here in this chat.
As a user using the app and not knowing anything about github, I had no idea that I need to "like" something to make timestamps appear.

There is no logical UX-valid connection between liking an entry and being able to view it's timestamp. It's not intuitive at all.

How about showing the tutorial together with the timestamp?

**Comment by KoalaBoomka** [comment] 2016-09-27 09:44
@0ki, thanks for your feedback. I will deliver your message to the corresponding team.

**Comment by 0ki** [comment] 2016-11-30 21:50
This is still a problem in 2.23. Would you like a screenshot?

**Comment by KoalaBoomka** [comment] 2016-12-01 09:19
@0ki, thanks for following a thread. We will notify you here when we make related changes.

**Comment by 0ki** [comment] 2017-10-06 10:56
This is a problem for new users. Please re-open.

**Comment by mikeger** [comment] 2017-10-11 10:19
@0ki hey, it should be fixed by this change https://github.com/wireapp/wire-ios/pull/1335

**Comment by mikeger** [comment] 2017-11-27 09:27
The issue was fixed in release 3.0.

**Closed by mikeger** 2017-11-27 09:27 UTC
