### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by PowerPress** [wireapp/wire-ios#2523] opened 2018-08-10 13:29 UTC
I'm curious where can I find what Metadata wire server keeps? Additionally are contacts stored in plain text?

**Comment by mikeger** [comment] 2018-08-10 13:56
Hey @PowerPress ! Thanks for the question. I believe it's not entirely iOS-client related, so consider reposting it at https://github.com/wireapp/wire . I will try to answer it, however.

You can find our elaborate privacy whitepaper here https://wire-docs.wire.com/download/Wire+Privacy+Whitepaper.pdf

If you are referring to the address book contacts, the answer can be found in Section 2.3

> Section 2.3: Address books are never stored on backend servers. If users grant client applications access to their address book, only email adresses and phone numbers are accessed. Each address book entry is hashed (using SHA-256) before being transmitted to the server. Those hashes are used to connect users (see section 2.2), but are only kept in volatile memory and not persisted.
No other information, such as names, addresses, birthdates, notes, etc. are extracted from the address books.

If you are referring to the wire connections, then section 3.2 can answer this:

> Wire maintains the following metadata about conversations on the backend servers:
> • Creator: The user who created the conversation.
> • Timestamp: The UTC timestamp when the conversation was created.
> • Participants list: The list of users who are participants of that conver- sation and their devices. This information is used by clients to display participants of the group and to perform end-to-end encryption between clients (see Wire Security Whitepaper for further details).
> • Conversation name: Every user can name or rename a group conversation. The above metadata is encrypted using transport encryption between the clients
and the server.


Additionally, you can request your account's metadata via the customer support.

**Comment by mikeger** [comment] 2018-08-24 11:45
Hey @PowerPress , if the issue is clarified please close it, otherwise I am happy to clarify any missing details.

**Closed** 2018-08-24 12:58 UTC
