### ISSUE TITLE
Siri Support (Featue Request)

### ISSUE THREAD

**Issue by malicioustoker** [wireapp/wire-ios#1581] opened 2018-01-05 22:27 UTC
I hope I’m not becoming too annoying with all these features requests, but you guys really are amazing, and I’ve gotten all my friends / family to move from iMessage to Wire. 😀 

On with the request:

Would y’all be able to add Siri support, for example, “Call X on Wire” or “Message X on Wire blah blah blah”

Thanks again!

**Comment by mikeger** [comment] 2018-01-08 14:38
Hey @malicioustoker ! Thanks for the feature request. I think this is definitely doable, also it is a great deal for the disabled people and those who is driving or having their hands busy. 

That said, this is not a small thing to do, so we need to have it scheduled in order to pull it off.

**Comment by mikeger** [comment] 2018-01-08 14:39
Duplicate of https://github.com/wireapp/wire-ios/issues/622

**Closed by mikeger** 2018-01-08 14:39 UTC
Labels: Feature request
