### ISSUE TITLE
list of "liked" messages

### ISSUE THREAD

**Issue by kopurando** [wireapp/wire-ios#794] opened 2017-03-05 10:00 UTC
"Liking" a message is a very interesting feature, I was looking for something like this since ICQ/IRC days, but unless it is possible to see a list of previously "liked" messages, this function feels incomplete. 
Unless I'm missing something, what's the purpose of liking a message, unless liked messages accumulate somewhere for later review (e.g. in Search screen)? I'd say likes' main purpose (apart from social grease) is to "star" important bits of a conversation, that should be addressed later.. Hope it makes sense.

Thanks once more.

**Comment by jenskasemets** [comment] 2017-03-06 15:00
Duplicate of #426

**Closed by jenskasemets** 2017-03-06 15:00 UTC
Labels: Feature request
