### ISSUE TITLE
No warning for a verified contact when adding a new device

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#1425] opened 2017-11-15 15:38 UTC
## Checklist (please check before submitting)

[ X] - I checked the existing issues, and the issue was not reported before.

## The problem

No warning for a verified contact when adding a new device

## Environment

* Wire version that exhibits the issue: 3.2
* Last Wire version that did not exhibit the issue (if applicable): N/A
* iOS version used to run Wire: 11.1.1
* iOS device type: iPhone SE
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wifi
* Exact date, time and timezone (only for the crash issues): N/A

## Details

- A is having a mobile 1
- B is having a mobile (iOS) and a desktop
- A is adding a new mobile to their account and send a message to B.
- A is sending a new message to B (see 1 below)
![pic1a](https://user-images.githubusercontent.com/1250795/32844420-abe0b7a4-ca22-11e7-94fa-08bb83f83292.png)
- B is answering with their Wire mobile.

There is no warning of losing the verified status (missed then the point of verifying contact).
Similar to #440 and give even more credit to https://github.com/wireapp/wire-webapp/issues/208

- B continues the conversation on Wire desktop and the warning is displayed there:
![pic1](https://user-images.githubusercontent.com/1250795/32844566-0f35bfac-ca23-11e7-80ba-804b2ca63ff8.png)

## Calling Debug logs (only for calling issues)

N/A

## Screenshots

Cf. upper

**Comment by mikeger** [comment] 2017-11-16 13:25
@IpsmLorem I cannot reproduce the issue, are you sure that all the clients where verified on mobile? Can I ask to try to reproduce it again?

NB: the verification status is not synchronized across your devices.

**Comment by IpsmLorem** [comment] 2017-11-16 17:57
Yes, I know that verification status is not synchronized (that could be a neat feature), and I'm **sure** that the recipient was verified on mobile.
I may try to reproduce with another recipient.

**Comment by mikeger** [comment] 2017-11-17 08:22
Thanks a lot, this would be very helpful!

PS sometimes the device can understand that there is a new client even earlier than the first message received from the user with the new client. May be the conversation status was updated earlier?

**Comment by IpsmLorem** [comment] 2017-11-17 13:26
I can reproduce and confirm:

- User A has a MobileA and a DesktopA
- User B has a MobileB and a DesktopB

Everyone is verified on all devices : 
- Mobile A -> MobileB + DesktopB = Verified user B
- Mobile B -> MobileA + DesktopA = Verified user A

1. Mobile A send a message to User B (Message 1):
![mobile](https://user-images.githubusercontent.com/1250795/32949223-59e023aa-cba2-11e7-8772-ca48afd4ed49.png)
2. User B add a Wire Web non temporary to their account: "WebB"
3. Mobile A send a message to user B (Message 2, see upper) --> No warning of unverified user !
4. User A try to send a Message 3 with their DesktopA --> Warning of unverified user as expected on desktop device
![pic desktop](https://user-images.githubusercontent.com/1250795/32949338-c6ce59aa-cba2-11e7-80c6-e2fdccd473d7.png)

Here is the B devices as seen on desktopA:
![devices](https://user-images.githubusercontent.com/1250795/32949384-e5598890-cba2-11e7-9d6a-cc6468bd2c33.png)

This is a bug, but https://github.com/wireapp/wire-webapp/issues/208 would save many trouble anyway. Having a way to  force wire to send ONLY to verified devices could give power back to the sender ;)

**Comment by IpsmLorem** [comment] 2017-12-17 18:33
Seems pretty nasty :(

**Comment by IpsmLorem** [comment] 2018-01-04 20:26
Still not marked as bug ?

**Comment by IpsmLorem** [comment] 2018-02-06 10:23
I can still reproduce the bug on: WIre iOS version 3.6 (2962) with the help of Wire desktop Version 3.0.2828
Wire for Web Version 2018.02.01.1026

**Comment by mikeger** [comment] 2018-02-06 10:51
@IpsmLorem we cannot really reproduce it, also it's tested with automation. May be we are missing some detail. May be you can make a screen recording of your steps to reproduce the issue? Thanks a lot.

**Comment by IpsmLorem** [comment] 2018-02-06 11:06
It's difficult to record a movie but I will try to be more understandable.

The initial setup:

- User A has a MobileA and a DesktopA
- User B has a MobileB and a DesktopB

Everyone is verified on all devices :
- MobileA has user B verified (MobileB + DesktopB)
- MobileB hase user A verfied (MobileA + DesktopA)

Steps to reproduce:

1. "User A" sends to "User B" via "Mobile A" : "Message 1"
2. "User B" logs to "https://app.wire.com" with a persistant session (public computer unchecked)
3. "User A" sends to "User B" via "Mobile A" : "Message 2"

"Mobile A" (Wire iOS 3.6) must have blocked the sending since the user is not verified anymore ; it didn't do that.

Wire "Desktop A" of "User A" had the job done: it warned the user that "User B" is not verified anymore.
At this point, if "User A" tries to send a message to "User B" via "Desktop A", Wire says : "User B started using a new device Do you still want to send your messages?" and blocks the sending.

**Comment by mikeger** [comment] 2018-02-06 11:14
@IpsmLorem you are absolutely sure that all devices of A and B are verified on mobile for user A? Do you see the shield in the conversation? Verification is local, so for user A you need to verify:
1. Own devices of A on MobileA
2. Devices of B on MobileA

**Comment by IpsmLorem** [comment] 2018-02-06 11:18
100% sure.
Here is a cap of User B's devices as seen on UserA Mobile:
![cap](https://user-images.githubusercontent.com/1250795/35856925-bf137158-0b37-11e8-9751-c1feee9861bf.png)

**Comment by IpsmLorem** [comment] 2018-02-06 11:21
That's right !
Not having "Desktop A" verified for "User A" on "mobile A", prevents to Warn "User A" from a verified breaking for "User B".
How strange is that ?

**Comment by mikeger** [comment] 2018-02-06 12:26
Thanks for the research. The end to end encryption system is designed to prevent the wire backend from being able to mangle with the messages. Therefore the device verification is currently local only. If the verification would be synced over the devices then BE could just potentially tell you that some devices are verified remotely.

You have to verify your own devices, since you send all your messages to all your devices to maintain the chat history.

We have a plan how to reduce the complexity in this, but it's not ready for being public yet.

**Comment by mikeger** [comment] 2018-02-06 12:27
I am closing the issue for now if no extra clarification is necessary.

**Closed by mikeger** 2018-02-06 12:27 UTC

**Comment by IpsmLorem** [comment] 2018-02-06 12:40
The system is cumbersome but efficient.
It could be improved by two simple features:
1. Rise shield only if all recipient's devices are verified AND all your own devices
2. https://github.com/wireapp/wire-webapp/issues/208
